name: Set up environment
description: Installs dependencies.

runs:
  using: "composite"
  steps:
    # python deps
    - name: Cache Python dependencies (uv)
      uses: actions/cache@v4
      with:
        path: |
          .venv
          ~/.cache/uv
        key: deps-python-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
        restore-keys: |
          deps-python-${{ runner.os }}-
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: Install uv
      run: pip install uv
      shell: bash
    - name: Install Python dependencies
      run: uv sync --locked --all-extras
      shell: bash

    # node deps
    - name: Cache Node.js dependencies (Yarn)
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          .yarn/cache
        key: deps-node-${{ runner.os }}-${{ hashFiles('package.json', 'yarn.lock') }}
        restore-keys: |
          deps-node-${{ runner.os }}-
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"
    - name: Install yarn
      run: npm install -g yarn
      shell: bash
    - name: Install Node.js dependencies
      run: yarn install --frozen-lockfile
      shell: bash
