name: build-time-key-fragment
description: Generate key fragments for caching based on build time

outputs:
  primary_key:
    description: "Primary cache key"
    value: ${{ steps.keygen.outputs.primary_key }}
  restore_key_1:
    description: "First restore key"
    value: ${{ steps.keygen.outputs.restore_key_1 }}
  restore_key_2:
    description: "Second restore key"
    value: ${{ steps.keygen.outputs.restore_key_2 }}
  restore_key_3:
    description: "Third restore key"
    value: ${{ steps.keygen.outputs.restore_key_3 }}

runs:
  using: "composite"
  steps:
    - name: |
        Generate a primary key for caching current artifact and
        restore keys for historical artifacts
      id: keygen
      run: |
        PRIMARY_KEY=$(date -u +'%Y-%m-%d-%H')
        RESTORE_KEY_1=$(date -u -d "-1 hour" +'%Y-%m-%d-%H')
        RESTORE_KEY_2=$(date -u -d "-2 hour" +'%Y-%m-%d-%H')
        RESTORE_KEY_3=$(date -u -d "-3 hour" +'%Y-%m-%d-%H')

        echo "primary_key=$PRIMARY_KEY" >> $GITHUB_OUTPUT
        echo "restore_key_1=$RESTORE_KEY_1" >> $GITHUB_OUTPUT
        echo "restore_key_2=$RESTORE_KEY_2" >> $GITHUB_OUTPUT
        echo "restore_key_3=$RESTORE_KEY_3" >> $GITHUB_OUTPUT
      shell: bash
      env:
        TZ: UTC
