name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Install dependencies
        run: uv pip install --system --group dev

      - name: Run ruff check
        run: ruff check .
      - name: Run ruff format
        run: ruff format --check .
      - name: Run mypy
        run: mypy .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Install dependencies
        run: uv sync --locked --all-extras
        
      - name: Run Django tests
        run: uv run python manage.py test
