name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Lock check
        run: uv lock --check
      - name: Install dependencies
        run: uv pip install --system --group dev
      - name: Run ruff check
        run: ruff check .
      - name: Run ruff format
        run: ruff format --check .
      - name: Run mypy
        run: mypy .
