name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      # formatters
      - name: Run ruff format
        run: uv run ruff format --check .
      - name: Run toml-sort
        run: uv run toml-sort --check $(git ls-files '*.toml')
      - name: Run prettier
        run: yarn run prettier --check $(git ls-files '*.yml' '*.yaml')

      # linters
      - name: Run ruff check
        run: uv run ruff check .
      - name: Block @nomerge comments
        run: '! git grep -n "@nomerge" -- ":!.github/workflows/test.yml"'

      # type check
      - name: Restore mypy cache
        uses: actions/cache/restore@v4
        with:
          path: .mypy_cache
          key: mypy-cache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            mypy-cache-${{ github.event.pull_request.base.ref || github.event.repository.default_branch }}-
      - name: Run dmypy
        run: |
          set -o pipefail
          uv run dmypy run -- --use-fine-grained-cache . | ./.github/scripts/mypy/log.sh
        continue-on-error: true
      - name: Run mypy
        run: |
          uv run mypy --cache-dir=/dev/null .

      # django tests
      - name: Run Django tests
        run: uv run python manage.py test
      - name: Run Django migrations check
        run: uv run python manage.py makemigrations --check

  update-stable-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - continuous-integration
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up git authentication
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Update stable tag
        run: |
          git tag -f stable
          git push origin stable --force
