name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      # formatters
      - name: Run ruff format
        run: uv run ruff format --check .
      - name: Run toml-sort
        run: uv run toml-sort --check $(git ls-files '*.toml')
      - name: Run prettier
        run: yarn run prettier --check $(git ls-files '*.yml' '*.yaml')

      # linters
      - name: Run ruff check
        run: uv run ruff check .
      - name: Run mypy
        run: uv run mypy .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run Django tests
        run: uv run python manage.py test
