name: Warm mypy cache

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-mypy-cache:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.check-cache.outputs.cache-hit }}
    steps:
      - name: Check cache
        id: check-cache
        uses: actions/cache/restore@v4
        with:
          path: .mypy_cache
          key: mypy-cache-${{ github.ref_name }}-${{ github.sha }}
          lookup-only: true

  warm-mypy-cache:
    runs-on: ubuntu-latest
    needs: [check-mypy-cache]
    if: ${{ needs.check-mypy-cache.outputs.cache-hit != 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run mypy
        run: uv run mypy --cache-fine-grained .

      - name: Store cache
        uses: actions/cache/save@v4
        with:
          path: .mypy_cache
          key: mypy-cache-${{ github.ref_name }}-${{ github.sha }}
