name: Warm mypy cache

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  warm-mypy-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run mypy
        run: mypy .

      - name: Get current date
        id: date
        run: |
          echo "year=$(date -u +'%Y')" >> $GITHUB_OUTPUT
          echo "month=$(date -u +'%m')" >> $GITHUB_OUTPUT
          echo "day=$(date -u +'%d')" >> $GITHUB_OUTPUT
          echo "hour=$(date -u +'%H')" >> $GITHUB_OUTPUT
        env:
          TZ: UTC

      - name: Store cache
        uses: actions/cache/save@v4
        with:
          path: .mypy_cache
          key: mypy-cache-${{ steps.date.outputs.year }}-${{ steps.date.outputs.month }}-${{ steps.date.outputs.day }}-${{ steps.date.outputs.hour }}
