name: Warm mypy cache

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  warm-mypy-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run mypy
        run: uv run mypy .

      - name: Generate build time key fragments
        uses: ./.github/actions/build-time-key-fragment
        id: keygen
      - name: Store cache
        uses: actions/cache/save@v4
        with:
          path: .mypy_cache
          key: mypy-cache-${{ steps.keygen.outputs.primary_key }}
